### ISSUE TITLE
[FEATURE] Add a Preference to choose the default color

### ISSUE THREAD

**Issue by Lswbanban** [leozide/leocad#231]
Right now, when you launch LeoCad, the default color is red, showing all the parts in the library as red.

It would be nice if we could choose the default color in the Preference. This would be the color selected by default when you launch the Application, or when you use "File > New".

**Comment by nathaneltitane** [comment]
This has already been mplemented in the parts list context menu: choose a part color, right click on any given part in the parts list and select 'Lock preview color'

Voila!

You're welcome.

**Comment by nathaneltitane** [comment]
@Lswbanban Feel free to dismiss this ticket once you read this!

**Comment by Lswbanban** [comment]
Thanks for the info. I didn't thought about checking the context menu.

I still recommend to add the option in the preference, because I guess this is where the user will search in priority, while keeping it also in the context menu (i.e. to have 2 ways of changing the default colors, but it basically changes the same setting).

**Comment by leozide** [comment]
I'll add an option.

**Comment by nathaneltitane** [comment]
@leozide  this is fixed. close issue?

**Comment by rsbx** [comment]
It's not really fixed since the suggested solution was to lock the 
interface color which does not the change the default color.

**Comment by Lswbanban** [comment]
Hello,

I'm confused, I cannot find the "Lock preview color" in the context menu of the part list, and I cannot find the option in the Preference window, in the 21.01 version. Is this option moved somewhere else ?

Thanks in advance.

**Comment by rsbx** [comment]
In the Parts widget, next to the search field, there is a gear icon. If 
you click that, you'll get see the checkbox in the list.

**Comment by Lswbanban** [comment]
Ok I finally found it, thanks. And I noticed that this color is retained if I restart LeoCAD.

As a general software design rules, I think that every settings that is saved in between sessions, should be accessible/editable in the Preferences Window. Because a user may change a settings through the UI, and many days after, when they relaunch the application they may forget where this settings was set, and they naturally think they can change it back to the settings/preference window.

This doesn't mean all the settings must be editable only through the Preference Window. Having shortcut through a more localized part of the UI is good, but it should also appear in the Preference window if it is persistent. If the setting is not persistent (not saved between session), this is perfectly fine to only access it through a local UI.

Thanks.
