### ISSUE TITLE
Wayland: Background looks transparent

### ISSUE THREAD

**Issue by hervyqa** [leozide/leocad#814]
**Describe the bug**
The background looks transparent, so the wallpaper is visible.

**To Reproduce**
1. Go to KDE/GNOME Wayland.
2. open LeoCAD.

**Expected behavior**
The background should be a solid color.

**Video**

https://user-images.githubusercontent.com/45872139/168728377-8322a6fb-b7ed-4df4-a5de-fde6b4ef1935.mp4

**Version (please complete the following information):**
 - OS: Void Linux KDE Wayland
 - LeoCAD Version 21.06

**Comment by hervyqa** [comment]
Solved with continuous build, running on xwayland.
`LeoCAD-Linux-d2f2277-x86_64.AppImage`

**Comment by hendursaga** [comment]
I got this as well, compiling the very latest version, but setting the theme from "Dark" to "System" fixed it, although I do like my Dark mode..

**Comment by kapouer** [comment]
This is still a problem in debian/trixie: the background is not repainted when leocad runs on wayland (gnome-shell).
To reproduce, just install leocad and run it in a gnome session.

Setting "System" theme in the UI fixes the issue, as @hendursaga mentionned.
However, setting the default theme to be "System" in https://github.com/leozide/leocad/blob/75e6537a225cdd77c6317e65fd12fdc3f59fd77f/common/lc_profile.cpp#L104
and relaunching leocad with that change (and no .config/LeoCad... file) doesn't improve the situation, one has to explicitely go in view preferences to toggle dark/system again.

Is there something that view preferences do that isn't done at start time ?

**Comment by schodet** [comment]
This was fixed in the debian package by cherry-picking a27b69c9fdb14de0092167151a18988ebdcf0692 and 5772688318f8b7df41c2b8ae5b5659f8c4b2c1e5.
